### ISSUE TITLE
Enhancing binary search code

### ISSUE THREAD

**Issue by vishalvibes** [houseofgeeks/CP-Dictionary#14]
Add a condition to exit if the array is not sorted in binary search code

**Comment by vishalvibes** [comment]
@Ritik-7 you should guide people who want to resolve this bug

**Comment by tusharjain0022** [comment]
I would like to solve this issue. May I start working on this ?
Note: My approach will be to define another function `bool isSorted(array address , size of array)` that will return true if array is sorted and false if not in `O(N)` time complexity and will exit or continue according to that. Or any suggestions for me?

**Comment by Vishal19111999** [comment]
@tusharjain0022 go ahead

**Comment by Vishal19111999** [comment]
@tusharjain0022 go ahead with fixing the C++ version

**Comment by vishalvibes** [comment]
This checking takes O(N) time...Is there any better way to avoid TLE even if the array is not sorted?
I have a simple solution that if the process takes more than log2(N) time then return

I would like to know whether there is a better solution to this

**Comment by jerryxu158** [comment]
I would also like to solve this issue, also, what does TLE mean

Edit: I'm trying to see if I can do sub o(n) time, although not entirely sure how to do that since to ensure the array is sorted I'm fairly certain we must visit every value at least once. I'm just going to commit an o(n) version first and get something temporary in while I try and see if there is a way to realistically shorten it

**Comment by vishalvibes** [comment]
@jerryxu158 true we can't check whether it's sorted or not O(N)...however we can avoid the execution from going into infinite loop...can we do something like if it visits the same element again...then exit?

**Comment by jerryxu158** [comment]
the version I committed should be incapable of going infinite due to it being a for loop with no nested loop.
 In regards to an exit condition regarding visiting the same value, I don't think that would be an issue regarding this variation since it would either catch a repeat twice in a row, as 37|37|... by returning false when the value isn't larger than the one before. or it would be a break in logic if a value is repeated later down the line since the value repeated would have to be smaller than a former value.
